# Generated by Django 2.2 on 2021-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_truck_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='current_location',
            field=models.CharField(default='23 Woodsworth AVE Redwood City CA 94086', max_length=255),
            preserve_default=False,
        ),
    ]
